import React, { useState, useRef, useEffect, Fragment } from 'react';
import { createPortal } from 'react-dom';
import InitialQuestionnaire from './InitialQuestionnaire';
import ReviewTab from './ReviewTab';
import GalleryTab from './GalleryTab';
import ClientProfile from './ClientProfile';
import { getChatMessages, addChatMessage, connectWebSocket, disconnectWebSocket, sendWebSocketMessage } from '../utils/chatStore';
import { usersApi, reviewsApi } from '../utils/api';
import { useDialog } from './ui/Dialog';
import { API_BASE_URL } from '../config';
import '../index.css';
