spring:
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 10MB
  datasource:
    url: jdbc:h2:file:./fitnessdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day

# Uncomment for PostgreSQL
# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/gym_app
#     username: postgres
#     password: password
#   jpa:
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-muddy-poetry-ab2hlmw1-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require}
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:npg_qhsvFmEC69eQ}
    driverClassName: org.postgresql.Driver
    connection-properties: prepareThreshold=0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

